version: '3.8'

services:
  react:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - public
    depends_on:
      - express
    volumes:
      - ./frontend/:/app
      - ./frontend/node_modules:/app/node_modules
    container_name: react_frontend

  express:
    build:
      context: backend
      target: server-dev
    ports:
      - 4040:4040
    networks:
      - public
      - mongo_db
    depends_on:
      - mongo
    volumes:
      - ./backend/:/app
      - ./backend/node_modules:/app/node_modules
    container_name: express_backend
  
  mongo:
    image: mongo:3.6-xenial
    environment:
      - MONGO_INITDB_DATABASE=databasename
    ports:
      - 27017:27017
    networks:
      - mongo_db
    volumes:
      - mongo_data:/data/db
    container_name: webapp_db


networks:
  public:
    driver: bridge
  mongo_db:
    driver: bridge

volumes:
  mongo_data:
    driver: local
